// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIu-AnFeLQMRLgJYeWA2ZWBCKcFwUC4AQ',
    appId: '1:496416968471:web:47da0fab36dd6554f03152',
    messagingSenderId: '496416968471',
    projectId: 'shapes-for-habits',
    authDomain: 'shapes-for-habits.firebaseapp.com',
    databaseURL: 'https://shapes-for-habits-default-rtdb.firebaseio.com',
    storageBucket: 'shapes-for-habits.appspot.com',
    measurementId: 'G-2VS1N3PKLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWlR6cMo4HPJbWA9PVqjwjmOQHre4UDjI',
    appId: '1:496416968471:android:71838e4360a2e29bf03152',
    messagingSenderId: '496416968471',
    projectId: 'shapes-for-habits',
    databaseURL: 'https://shapes-for-habits-default-rtdb.firebaseio.com',
    storageBucket: 'shapes-for-habits.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOWMhAVH5zyS_WX2TBbhot7_UoClRxnxY',
    appId: '1:496416968471:ios:045088936bea37bff03152',
    messagingSenderId: '496416968471',
    projectId: 'shapes-for-habits',
    databaseURL: 'https://shapes-for-habits-default-rtdb.firebaseio.com',
    storageBucket: 'shapes-for-habits.appspot.com',
    androidClientId: '496416968471-vpidc8598s6j1e5f6dbo9qqe677d5fps.apps.googleusercontent.com',
    iosClientId: '496416968471-7o88cdpsjqfibn4g2bd7ocbvks6q7ugq.apps.googleusercontent.com',
    iosBundleId: 'com.example.vs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOWMhAVH5zyS_WX2TBbhot7_UoClRxnxY',
    appId: '1:496416968471:ios:045088936bea37bff03152',
    messagingSenderId: '496416968471',
    projectId: 'shapes-for-habits',
    databaseURL: 'https://shapes-for-habits-default-rtdb.firebaseio.com',
    storageBucket: 'shapes-for-habits.appspot.com',
    androidClientId: '496416968471-vpidc8598s6j1e5f6dbo9qqe677d5fps.apps.googleusercontent.com',
    iosClientId: '496416968471-7o88cdpsjqfibn4g2bd7ocbvks6q7ugq.apps.googleusercontent.com',
    iosBundleId: 'com.example.vs',
  );
}
